/* Pendar Future Observatory — research-first public prototype. */
const FUTURE_TOPICS=[
  {id:"power",title:"انتقال قدرت و ساختار نهادها",words:["انتقال قدرت","ساختار قدرت","حکومت موقت","گذار سیاسی","جانشینی","تغییر نظام"]},
  {id:"law",title:"حقوق، قانون اساسی و عدالت انتقالی",words:["قانون اساسی","عدالت انتقالی","حقوق شهروندی","حقوق بشر","قوه قضاییه"]},
  {id:"security",title:"امنیت و تداوم خدمات عمومی",words:["نیروهای مسلح","امنیت داخلی","خدمات عمومی","بحران امنیتی","ارتش","پلیس"]},
  {id:"economy",title:"اقتصاد و مدیریت بحران",words:["تورم","بودجه","بانک مرکزی","ریال","بیکاری","تحریم"]},
  {id:"society",title:"جامعه، نمایندگی و مشارکت",words:["اعتراضات","جامعه مدنی","انتخابات","اعتصاب","ائتلاف سیاسی"]},
  {id:"foreign",title:"روابط خارجی و محیط منطقه‌ای",words:["دیپلماسی","آمریکا","اسرائیل","روابط خارجی","اروپا","مذاکرات"]}
];
const futureEsc=x=>String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function futureStoryTitle(s){return String(s.headline_fa||s.title_fa||s.title||"");}
function futureStoryDate(s){let d=new Date(s.published_at||s.date||"");return Number.isNaN(d.getTime())?"":d.toLocaleDateString("fa-IR");}
async function futureLoadStories(){try{let r=await fetch("/data/stories.json",{cache:"no-store"});if(!r.ok)throw Error(r.status);let data=await r.json();return Array.isArray(data)?data:Array.isArray(data.stories)?data.stories:[];}catch(_){return null;}}
function futureFrame(inner){return '<div class="future-layout"><div class="future-topline"><a href="/future/">آینده‌بان</a><span>پژوهش، نه پیشگویی</span></div>'+inner+'</div>';}
function futureHomeHTML(){return futureFrame('<div class="future-hero"><span class="future-eyebrow">آزمایشگاه آینده‌پژوهی پندار</span><h1>آینده‌بان</h1><p>از خبرهای امروز تا پرسش‌های فردا؛ نشانه‌ها، فرضیه‌ها و مسیرهای مختلف آینده را با منابع روشن و تاریخ بازبینی دنبال می‌کنیم.</p></div><div class="future-cards"><a href="/future/transition/" class="future-card"><span>پرونده نخست</span><h2>اطلس گذار</h2><p>مسائل انتقال قدرت، نهادها، قانون، اقتصاد، امنیت و جامعه؛ با تفکیک سناریوهای اکتشافی از طرح‌های تجویزی.</p><b>ورود به اطلس ←</b></a><div class="future-card future-muted"><span>در حال توسعه</span><h2>روندهای بلندمدت</h2><p>روندسنجی و مقایسه تاریخی در آینده با داده‌های ساختاریافته و قابل بازبینی.</p></div></div><a href="/future/method/" class="future-card" style="display:block;margin-top:20px"><span>زیرساخت روش‌شناسی</span><h2>روش آینده‌بان و دیده‌بان گذار</h2><p>طبقه‌بندی رویدادها، محورها، پرسش‌های پایش، ساختار سناریوها و قواعد استناد.</p><b>مشاهده چارچوب ←</b></a><div class="future-note"><b>روش کار</b><p>این نسخه آغاز یک پروژه پژوهشی است. درج خبر در دیده‌بان به معنای تأیید آن خبر یا افزایش احتمال یک سناریو نیست.</p></div>');}
function futureTransitionHTML(){return futureFrame('<a class="future-back" href="/future/">← آینده‌بان</a><div class="future-hero"><span class="future-eyebrow">پرونده پژوهشی / نسخه اولیه</span><h1>اطلس گذار</h1><p>پژوهش درباره مسیرهای ممکن دگرگونی و انتقال قدرت در ایران؛ تفکیک آنچه ممکن است رخ دهد، آنچه پیشنهاد می‌شود و آنچه مطلوب دانسته می‌شود.</p></div><div class="future-principles"><span>سناریوی اکتشافی: چه ممکن است؟</span><span>طرح تجویزی: چه باید کرد؟</span><span>چشم‌انداز مطلوب: چه می‌خواهیم؟</span></div><h2 class="future-heading">موضوع‌های اطلس</h2><div class="future-topics">'+FUTURE_TOPICS.map(t=>'<a href="#future-watch" data-future-topic="'+t.id+'" class="future-topic"><h3>'+futureEsc(t.title)+'</h3><span>مشاهده نشانه‌های خبری مرتبط ←</span></a>').join('')+'</div><div class="future-watch" id="future-watch"><div class="future-watch-head"><div><span class="future-eyebrow">پایش موضوعی آزمایشی</span><h2>دیده‌بان گذار</h2><p>خبرهای مرتبط با کلیدواژه‌ها؛ بدون امتیازدهی به احتمال گذار یا نتیجه‌گیری خودکار.</p></div><span id="future-watch-stamp"></span></div><div class="future-filters">'+FUTURE_TOPICS.map(t=>'<button type="button" data-future-filter="'+t.id+'">'+futureEsc(t.title)+'</button>').join('')+'</div><div id="future-evidence" aria-live="polite"><p>در حال بررسی داده‌های خبری پندار…</p></div></div><section class="future-library"><a class="future-card" style="display:block;margin-bottom:18px" href="/future/transition/fattahi/"><span>پرونده پژوهشی نخست</span><h2>معماری حکمرانی گذار در مدل سجاد فتاحی</h2><p>مرجع عالی گذار، دولت موقت، مهستان، دادگستری، دیدبانی و دیگر نهادها؛ همراه با ارجاع صفحه‌ای.</p><b>مشاهده مدل ←</b></a><h2 class="future-heading">کتابخانه پژوهشی</h2><p class="future-method">سه اثر سجاد فتاحی؛ شناسنامه‌ها ثبت شده‌اند و پرونده‌های تحلیلی در حال آماده‌سازی‌اند.</p><div id="future-research-books">در حال بارگذاری کتاب‌ها…</div></section>');}
async function showFuture(section=""){show("future");setTab("");const sub=section==="transition"||section==="transition/fattahi";setHash(section==="method"?"future/method":section==="transition/fattahi"?"future/transition/fattahi":sub?"future/transition":"future");document.title=(sub?"اطلس گذار":"آینده‌بان")+" | پندار";const root=document.getElementById("future-content");root.innerHTML=section==="method"?futureFrame('<a class="future-back" href="/future/">← آینده‌بان</a><div class="future-hero"><span class="future-eyebrow">چارچوب پژوهشی نسخه اول</span><h1>روش آینده‌بان</h1><p>از داده خبری تا شواهد قابل سنجش و سناریوهای قابل بازبینی</p></div><div id="future-method-view">در حال دریافت چارچوب…</div>'):section==="transition/fattahi"?futureFrame('<a class="future-back" href="/future/transition/">← اطلس گذار</a><div class="future-hero"><span class="future-eyebrow">پژوهش‌های سجاد فتاحی</span><h1>معماری حکمرانی دوران گذار</h1><p>مرور ساختار نهادی پیشنهادی در کتاب «ایران؛ پیش از آینده»</p></div><div id="future-fattahi-model">در حال بارگذاری مدل مستند…</div>'):sub?futureTransitionHTML():futureHomeHTML();if(section==="method"){futureLoadMethod();return;}if(section==="transition/fattahi"){futureLoadFattahi();return;}if(!sub)return;root.querySelectorAll("[data-future-topic]").forEach(a=>a.addEventListener("click",()=>{futureChoose(a.dataset.futureTopic);}));root.querySelectorAll("[data-future-filter]").forEach(b=>b.addEventListener("click",()=>futureChoose(b.dataset.futureFilter)));futureChoose("power");futureLoadBooks();}
let futureStoriesCache=null;
async function futureChoose(id){let t=FUTURE_TOPICS.find(x=>x.id===id)||FUTURE_TOPICS[0];document.querySelectorAll("[data-future-filter]").forEach(b=>b.classList.toggle("selected",b.dataset.futureFilter===t.id));const box=document.getElementById("future-evidence");if(!box)return;box.innerHTML="<p>در حال بازیابی خبرهای مرتبط…</p>";if(futureStoriesCache===null)futureStoriesCache=await futureLoadStories()||[];if(!document.getElementById("future-evidence"))return;let stories=futureStoriesCache.filter(s=>{let text=(futureStoryTitle(s)+" "+String(s.summary_fa||"")).toLowerCase();return t.words.some(w=>text.includes(w.toLowerCase()));}).sort((a,b)=>new Date(b.published_at||0)-new Date(a.published_at||0)).slice(0,12);document.getElementById("future-watch-stamp").textContent="بازبینی هنگام مشاهده: "+new Date().toLocaleDateString("fa-IR");box.innerHTML=stories.length?'<p class="future-method">نتایج تطبیق واژگانی با خبرهای اخیر، نه مجموعه شواهد تأییدشده آینده‌پژوهی.</p>'+stories.map(s=>'<a class="future-evidence-row" href="/story/'+encodeURIComponent(s.id)+'/"><span>'+futureEsc(futureStoryDate(s))+'</span><strong>'+futureEsc(futureStoryTitle(s))+'</strong><small>مشاهده خبر و منابع ←</small></a>').join(''):'<p class="future-empty">در داده‌های خبری فعلی، موردی با کلیدواژه‌های این محور پیدا نشد. این به معنی نبود رویداد مرتبط نیست.</p>';}

async function futureLoadBooks(){const box=document.getElementById("future-research-books");if(!box)return;try{const r=await fetch("/data/future-research-books.json");if(!r.ok)throw Error("catalog");const d=await r.json();if(!document.getElementById("future-research-books"))return;box.innerHTML='<div class="future-topics">'+(d.books||[]).map(b=>'<article class="future-topic"><span class="future-eyebrow">'+futureEsc(b.kind)+'</span><h3>'+futureEsc(b.title)+'</h3><p>'+futureEsc(b.subtitle)+'</p><small>'+futureEsc(b.author)+' · '+futureEsc(b.publisher)+' · '+futureEsc(b.pages_pdf)+' صفحه PDF</small><p class="future-method">'+futureEsc(b.source_status)+'</p></article>').join("")+'</div>';}catch(_){box.textContent="فهرست پژوهش‌ها فعلاً در دسترس نیست."}}

async function futureLoadFattahi(){const root=document.getElementById("future-fattahi-model");if(!root)return;try{const r=await fetch("/data/future-fattahi-model.json");if(!r.ok)throw Error("unavailable");const d=await r.json();if(!document.getElementById("future-fattahi-model"))return;root.innerHTML='<div class="future-note"><b>'+futureEsc(d.status)+'</b><p>'+futureEsc(d.book)+' · '+futureEsc(d.chapter)+'</p></div><h2 class="future-heading">دو الگوی مرجع عالی گذار</h2><div class="future-cards">'+d.models.map(m=>'<article class="future-card"><h2>'+futureEsc(m.name)+'</h2><p>'+futureEsc(m.subtitle)+'</p><small>کتاب، صفحه '+futureEsc(m.page)+'</small></article>').join("")+'</div><h2 class="future-heading">نهادهای پیشنهادی در مدل نویسنده</h2><div class="future-topics">'+d.institutions.map(x=>'<details class="future-topic"><summary><strong>'+futureEsc(x.name)+'</strong></summary><p>'+futureEsc(x.role)+'</p><small>ارجاع کتاب: ص '+futureEsc(x.page)+'</small></details>').join("")+'</div><div class="future-note"><b>درباره استنادها</b><p>'+futureEsc(d.research_note)+'</p></div>';}catch(_){root.textContent="اطلاعات پژوهشی در دسترس نیست."}}

async function futureLoadMethod(){const root=document.getElementById("future-method-view");if(!root)return;try{const res=await fetch("/data/future-methodology.json",{cache:"no-store"});if(!res.ok)throw Error(res.status);const d=await res.json();if(!document.getElementById("future-method-view"))return;root.innerHTML='<div class="future-note"><strong>این صفحه چارچوب طراحی است، نه داشبوردِ دارای داده ارزیابی‌شده.</strong><p>ثبت هشدار یا برآورد احتمالات تنها پس از بررسی شواهد و اجرای فرایند تحریری انجام می‌شود.</p></div><h2 class="future-heading">سه اصل طراحی</h2><div class="future-topics">'+d.principles.map(x=>'<article class="future-topic"><h3>'+futureEsc(x.title)+'</h3><p>'+futureEsc(x.detail)+'</p><a href="'+futureEsc(x.url)+'" target="_blank" rel="noopener noreferrer"><small>منبع: '+futureEsc(x.source)+' ↗</small></a></article>').join("")+'</div><h2 class="future-heading">محورهای رصد و پرسش‌های هشدار</h2><div class="future-topics">'+d.axes.map(x=>'<details class="future-topic"><summary><strong>'+futureEsc(x.title)+'</strong></summary><ul>'+x.signals.map(y=>'<li>'+futureEsc(y)+'</li>').join("")+'</ul><small>موضوع پایش؛ هنوز امتیازدهی نشده</small></details>').join("")+'</div><h2 class="future-heading">ساختار پرونده‌های آینده</h2><div class="future-cards"><div class="future-card"><h3>پرونده رویداد</h3><p>'+d.event_record_fields.map(futureEsc).join(" · ")+'</p></div><div class="future-card"><h3>پرونده سناریو</h3><p>'+d.scenario_record_fields.map(futureEsc).join(" · ")+'</p></div></div><h2 class="future-heading">ضوابط تحریریه</h2><div class="future-note"><ul>'+d.editorial_rules.map(x=>'<li>'+futureEsc(x)+'</li>').join("")+'</ul></div>';}catch(_){root.textContent="فایل روش‌شناسی هنوز روی میزبان موجود نیست."}}
