(function(){"use strict";
const axes={authority:"مرجع عالی گذار",executive:"دیوان گذار",justice:"دادگستری گذار",mahestan:"مجلس مهستان",security:"نیروهای نظامی و امنیتی",economy:"نهادهای اقتصادی",watch:"نهاد دیدبانی",assembly:"مجلس شورای ملی"};
const words={authority:["انتقال قدرت","حکومت موقت","تمرکز قدرت"],executive:["خدمات عمومی","دولت موقت"],justice:["قوه قضاییه","دادگستری","عدالت انتقالی"],mahestan:["قانون اساسی","مجلس مؤسسان"],security:["نیروهای مسلح","ارتش","سپاه"],economy:["بانک مرکزی","اقتصاد","تورم"],watch:["شفافیت","پاسخگویی","نظارت"],assembly:["مجلس","انتخابات","نمایندگی"]};
let stories=[],drafts=[],baseIndex={};
const $=id=>document.getElementById(id);
function safeId(x){return typeof x==="string"&&/^[\w-]{8,100}$/.test(x)}
function norm(s){return String(s||"").replace(/[يى]/g,"ی").replace(/ك/g,"ک").replace(/\u200c/g," ").toLowerCase()}
const value=id=>$(id).value.trim();
const urls=id=>value(id).split("\n").map(s=>s.trim()).filter(s=>/^https?:\/\/[^\s]+$/i.test(s));
function add(tag,parent,txt){const x=document.createElement(tag);if(txt!==undefined)x.textContent=txt;parent.appendChild(x);return x}
function renderCandidates(){const root=$("candidates");root.replaceChildren();const axis=value("axis");const arr=stories.filter(s=>words[axis].some(w=>norm(s.headline_fa||s.title_fa||s.title).includes(norm(w)))).slice(0,15);if(!arr.length){add("p",root,"موردی در فهرست خبری فعلی یافت نشد؛ این نتیجه به معنی نبود خبر مرتبط نیست.");return;}for(const s of arr){const div=add("div",root);div.className="entry";add("div",div,s.headline_fa||s.title_fa||s.title);const b=add("button",div,"انتخاب برای بررسی");b.type="button";b.className="secondary";b.addEventListener("click",()=>{$("story").value=s.id;$("claim").value=s.headline_fa||s.title_fa||s.title||""});}}
function renderDrafts(){const root=$("drafts");root.replaceChildren();if(!drafts.length){add("p",root,"هنوز موردی ثبت نشده است.");return;}for(const d of drafts){const div=add("div",root);div.className="entry";add("strong",div,d.claim);add("p",div,d.status+" · "+d.reviewed_at+" · نسخه "+d.revision);add("small",div,d.rationale);}}
function exportDraft(){const blob=new Blob([JSON.stringify({schema:1,exported_at:new Date().toISOString(),notice:"UNPUBLISHED EDITORIAL DRAFT: human approval required",records:drafts},null,2)],{type:"application/json;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="future-review-drafts.json";document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
async function boot(){const sel=$("axis");for(const [k,t] of Object.entries(axes)){const x=add("option",sel,t);x.value=k;}try{const r=await fetch("/data/stories.json",{cache:"no-store"});if(!r.ok)throw Error(r.status);const d=await r.json();stories=(Array.isArray(d)?d:d.stories||[]).filter(x=>safeId(x.id)&&String(x.headline_fa||x.title_fa||x.title||"").trim());}catch(_){$("candidates").textContent="دریافت خبرها ممکن نشد؛ می‌توانید شناسه خبر را دستی وارد کنید.";}try{const r=await fetch("/data/future-evidence-reviews.json",{cache:"no-store"});if(r.ok){const d=await r.json();for(const x of d.records||[]){baseIndex[x.story_id+"|"+x.axis]=x;}}}catch(_){}sel.addEventListener("change",renderCandidates);renderCandidates();
$("reviewform").addEventListener("submit",e=>{e.preventDefault();const id=value("story"),axis=value("axis");if(!safeId(id)){alert("شناسه خبر معتبر نیست.");return;}const key=id+"|"+axis,previous=[...drafts].reverse().find(x=>x.story_id===id&&x.axis===axis)||baseIndex[key];const oldHistory=previous?.history||[];const history=previous?[...oldHistory,{at:previous.reviewed_at,status:previous.status,rationale:previous.rationale}]:[];const d={story_id:id,axis,status:value("status"),claim:value("claim"),primary_sources:urls("primary"),independent_sources:urls("independent"),contradicting_evidence:value("contrary"),reviewer:value("reviewer"),reviewed_at:new Date().toISOString(),rationale:value("rationale"),revision:Number(previous?.revision||0)+1,history};drafts.push(d);renderDrafts();});$("export").addEventListener("click",exportDraft);}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot);else boot();
})();