/* Pendar Future Observatory — research-first public prototype. */
const FUTURE_TOPICS=[
  {id:"power",title:"انتقال قدرت و ساختار نهادها",words:["انتقال قدرت","ساختار قدرت","حکومت موقت","گذار سیاسی","جانشینی","تغییر نظام"]},
  {id:"law",title:"حقوق، قانون اساسی و عدالت انتقالی",words:["قانون اساسی","عدالت انتقالی","حقوق شهروندی","حقوق بشر","قوه قضاییه"]},
  {id:"security",title:"امنیت و تداوم خدمات عمومی",words:["نیروهای مسلح","امنیت داخلی","خدمات عمومی","بحران امنیتی","ارتش","پلیس"]},
  {id:"economy",title:"اقتصاد و مدیریت بحران",words:["تورم","بودجه","بانک مرکزی","ریال","بیکاری","تحریم"]},
  {id:"society",title:"جامعه، نمایندگی و مشارکت",words:["اعتراضات","جامعه مدنی","انتخابات","اعتصاب","ائتلاف سیاسی"]},
  {id:"foreign",title:"روابط خارجی و محیط منطقه‌ای",words:["دیپلماسی","آمریکا","اسرائیل","روابط خارجی","اروپا","مذاکرات"]}
];
const futureEsc=x=>String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function futureStoryTitle(s){return String(s.headline_fa||s.title_fa||s.title||"");}
function futureStoryDate(s){let d=new Date(s.published_at||s.date||"");return Number.isNaN(d.getTime())?"":d.toLocaleDateString("fa-IR");}
async function futureLoadStories(){try{let r=await fetch("/data/stories.json",{cache:"no-store"});if(!r.ok)throw Error(r.status);let data=await r.json();return Array.isArray(data)?data:Array.isArray(data.stories)?data.stories:[];}catch(_){return null;}}
function futureFrame(inner){return '<div class="future-layout"><div class="future-topline"><a href="/future/">آینده‌بان</a><span>پژوهش، نه پیشگویی</span></div>'+inner+'</div>';}
function futureHomeHTML(){return futureFrame('<div class="future-hero"><span class="future-eyebrow">آزمایشگاه آینده‌پژوهی پندار</span><h1>آینده‌بان</h1><p>از خبرهای امروز تا پرسش‌های فردا؛ نشانه‌ها، فرضیه‌ها و مسیرهای مختلف آینده را با منابع روشن و تاریخ بازبینی دنبال می‌کنیم.</p></div><div class="future-cards"><a href="/future/transition/" class="future-card"><span>پرونده نخست</span><h2>اطلس گذار</h2><p>مسائل انتقال قدرت، نهادها، قانون، اقتصاد، امنیت و جامعه؛ با تفکیک سناریوهای اکتشافی از طرح‌های تجویزی.</p><b>ورود به اطلس ←</b></a><div class="future-card future-muted"><span>در حال توسعه</span><h2>روندهای بلندمدت</h2><p>روندسنجی و مقایسه تاریخی در آینده با داده‌های ساختاریافته و قابل بازبینی.</p></div></div><div class="future-note"><b>روش کار</b><p>این نسخه آغاز یک پروژه پژوهشی است. درج خبر در دیده‌بان به معنای تأیید آن خبر یا افزایش احتمال یک سناریو نیست. تا زمان بررسی کتاب‌ها و پژوهش‌ها، هیچ سناریوی منتسب به اشخاص تولید نمی‌شود.</p></div>');}
function futureTransitionHTML(){return futureFrame('<a class="future-back" href="/future/">← آینده‌بان</a><div class="future-hero"><span class="future-eyebrow">پرونده پژوهشی / نسخه اولیه</span><h1>اطلس گذار</h1><p>پژوهش درباره مسیرهای ممکن دگرگونی و انتقال قدرت در ایران؛ تفکیک آنچه ممکن است رخ دهد، آنچه پیشنهاد می‌شود و آنچه مطلوب دانسته می‌شود.</p></div><div class="future-principles"><span>سناریوی اکتشافی: چه ممکن است؟</span><span>طرح تجویزی: چه باید کرد؟</span><span>چشم‌انداز مطلوب: چه می‌خواهیم؟</span></div><h2 class="future-heading">موضوع‌های اطلس</h2><div class="future-topics">'+FUTURE_TOPICS.map(t=>'<a href="#future-watch" data-future-topic="'+t.id+'" class="future-topic"><h3>'+futureEsc(t.title)+'</h3><span>مشاهده نشانه‌های خبری مرتبط ←</span></a>').join('')+'</div><div class="future-watch" id="future-watch"><div class="future-watch-head"><div><span class="future-eyebrow">پایش موضوعی آزمایشی</span><h2>دیده‌بان گذار</h2><p>خبرهای مرتبط با کلیدواژه‌ها؛ بدون امتیازدهی به احتمال گذار یا نتیجه‌گیری خودکار.</p></div><span id="future-watch-stamp"></span></div><div class="future-filters">'+FUTURE_TOPICS.map(t=>'<button type="button" data-future-filter="'+t.id+'">'+futureEsc(t.title)+'</button>').join('')+'</div><div id="future-evidence" aria-live="polite"><p>در حال بررسی داده‌های خبری پندار…</p></div></div><div class="future-note"><b>گام بعد: کتابخانه پژوهشی</b><p>متون کتاب‌های سجاد فتاحی و آثار دیگر پژوهشگران پس از دریافت و بررسی مستند اضافه می‌شوند. در حال حاضر هیچ نظری به نویسنده‌ای نسبت داده نشده است. هر ادعا در آینده باید با ارجاع دقیق به اثر و صفحه منتشر شود.</p></div>');}
async function showFuture(section=""){show("future");setTab("");const sub=section==="transition";setHash(sub?"future/transition":"future");document.title=(sub?"اطلس گذار":"آینده‌بان")+" | پندار";const root=document.getElementById("future-content");root.innerHTML=sub?futureTransitionHTML():futureHomeHTML();if(!sub)return;root.querySelectorAll("[data-future-topic]").forEach(a=>a.addEventListener("click",()=>{futureChoose(a.dataset.futureTopic);}));root.querySelectorAll("[data-future-filter]").forEach(b=>b.addEventListener("click",()=>futureChoose(b.dataset.futureFilter)));futureChoose("power");}
let futureStoriesCache=null;
async function futureChoose(id){let t=FUTURE_TOPICS.find(x=>x.id===id)||FUTURE_TOPICS[0];document.querySelectorAll("[data-future-filter]").forEach(b=>b.classList.toggle("selected",b.dataset.futureFilter===t.id));const box=document.getElementById("future-evidence");if(!box)return;box.innerHTML="<p>در حال بازیابی خبرهای مرتبط…</p>";if(futureStoriesCache===null)futureStoriesCache=await futureLoadStories()||[];if(!document.getElementById("future-evidence"))return;let stories=futureStoriesCache.filter(s=>{let text=(futureStoryTitle(s)+" "+String(s.summary_fa||"")).toLowerCase();return t.words.some(w=>text.includes(w.toLowerCase()));}).sort((a,b)=>new Date(b.published_at||0)-new Date(a.published_at||0)).slice(0,12);document.getElementById("future-watch-stamp").textContent="بازبینی هنگام مشاهده: "+new Date().toLocaleDateString("fa-IR");box.innerHTML=stories.length?'<p class="future-method">نتایج تطبیق واژگانی با خبرهای اخیر، نه مجموعه شواهد تأییدشده آینده‌پژوهی.</p>'+stories.map(s=>'<a class="future-evidence-row" href="/story/'+encodeURIComponent(s.id)+'/"><span>'+futureEsc(futureStoryDate(s))+'</span><strong>'+futureEsc(futureStoryTitle(s))+'</strong><small>مشاهده خبر و منابع ←</small></a>').join(''):'<p class="future-empty">در داده‌های خبری فعلی، موردی با کلیدواژه‌های این محور پیدا نشد. این به معنی نبود رویداد مرتبط نیست.</p>';}
