/* Pendar radar family: shared news, profile identities and sourced snapshots. */
let ISR=null, ISR_FIGURES=[];
let ISR_SELECTED=new Set();
let ISR_NEWS=[];
let ISR_NEWS_FILTER='all';
function isrDate(value){const d=new Date(value);return Number.isNaN(+d)?'':d.toLocaleDateString('fa-IR',{year:'numeric',month:'long',day:'numeric'});}
function isrNewsMatches(row,person=null){
 const t=[row.headline_fa,row.topic_fa,row.summary_fa].filter(Boolean).join(' ').replace(/ي/g,'ی').replace(/ك/g,'ک').replace(/‌/g,' ');
 if(person)return [person.name_fa,...(person.aliases||[])].some(n=>n&&t.includes(n.replace(/‌/g,' ')));
 return /اسرائیل|نتانیاهو|نفتالی بنت|یائیر لاپید|آیزنکوت|ایزنکوت|بن گویر|اسموتریچ|کنست/.test(t);
}
function isrProfileNews(person){return ISR_NEWS.filter(n=>isrNewsMatches(n,person)).slice(0,6);}
function isrPhoto(person){const existing=ISR_FIGURES.find(f=>f.handle===person.handle);const src=existing?.avatar||person.avatar;return src?`<img src="${esc(src)}" alt="${esc(person.name_fa)}" loading="lazy" onerror="this.hidden=true">`:'';}
function isrPersonCard(p){const party=ISR.parties.find(x=>x.id===p.party_id);return `<a class="isr-person" href="/figure/${encodeURIComponent(p.handle)}/">${isrPhoto(p)}<div><h3>${esc(p.name_fa)}</h3><small>${esc(p.role_fa)}</small><span>${esc(party?.name_fa||'')} · صفحه چهره ←</span></div></a>`;}
function isrNewsCard(n){const url=n._internal?`/story/${encodeURIComponent(n.id)}/`:n.url;return `<a class="isr-news-card" href="${esc(url)}" ${n._internal?'':'target="_blank" rel="noopener"'}><small>${esc(n.source_name||((n.sources||[])[0]?.source_name)||'سرخط پندار')} · ${esc(isrDate(n.published_at||n.last_seen_at))}</small><h3>${esc(n.headline_fa||n.topic_fa)}</h3><p>${esc(String(n.summary_fa||'').slice(0,190))}</p><span>${n._internal?'خبر در پندار':'منبع اصلی'} ←</span></a>`;}
function isrPositionCard(r){const p=ISR.people.find(x=>x.handle===r.handle);return `<article class="isr-position">${p?`<a href="/figure/${encodeURIComponent(p.handle)}/">${isrPhoto(p)}<b>${esc(p.name_fa)}</b></a>`:''}<p>${esc(r.summary_fa)}</p><a href="${esc(r.url)}" target="_blank" rel="noopener">${esc(r.source)} · ${esc(isrDate(r.date))} ↗</a></article>`;}
function isrProfileSection(handle){if(!ISR)return '';const p=ISR.people.find(x=>x.handle===handle);if(!p)return '';const news=isrProfileNews(p);const positions=ISR.iran_positions.filter(r=>r.handle===handle);return `<section class="isr-profile"><a class="isr-back" href="/israel-radar/">رادار اسرائیل · رقابت احزاب و انتخابات ←</a>${positions.length?'<h3>مواضع مستند درباره ایران</h3><div class="isr-news-grid">'+positions.map(isrPositionCard).join('')+'</div>':''}${news.length?'<h3>خبرهای مرتبط با این چهره</h3><div class="isr-news-grid">'+news.map(isrNewsCard).join('')+'</div>':''}</section>`;}
async function loadISRadar(){if(ISR)return ISR;ISR=await getJSON(DATA+'/pendar-israel-radar.json');return ISR;}
async function loadISRNews(){try{const all=await getJSON(DATA+'/stories.json');const items=Array.isArray(all)?all:all.stories||[];ISR_NEWS=items.filter(n=>isrNewsMatches(n)).map(n=>({...n,_internal:true})).sort((a,b)=>String(b.published_at||b.last_seen_at||'').localeCompare(String(a.published_at||a.last_seen_at||'')));}catch(_){ISR_NEWS=[];}}
function isrRefreshCoalition(){
 const total=ISR.parties.filter(p=>ISR_SELECTED.has(p.id)).reduce((s,p)=>s+p.seats,0);
 const el=document.getElementById('isr-coalition-total');if(!el)return;
 const left=Math.max(0,ISR.majority-total);el.innerHTML=`<b>${faN(total)}</b><span>از ${faN(ISR.majority)} کرسی برای اکثریت مطلق<br><small>${total>=ISR.majority?'این ترکیب از نظر تعداد کرسی به حد اکثریت رسیده است':faN(left)+' کرسی دیگر لازم دارد'}</small></span>`;
 document.getElementById('isr-coalition-progress').style.width=Math.min(100,total/ISR.total_seats*100)+'%';
}
function isrToggleParty(id,checked){checked?ISR_SELECTED.add(id):ISR_SELECTED.delete(id);isrRefreshCoalition();}
function isrSetNewsFilter(value){ISR_NEWS_FILTER=value;isrRenderNews();}
function isrRenderNews(){const el=document.getElementById('isr-news');if(!el)return;const rows=ISR_NEWS.filter(n=>ISR_NEWS_FILTER==='all'||/انتخاب|کنست|ائتلاف|نظرسنجی|لیکود/.test(n.headline_fa+' '+n.summary_fa)).slice(0,12);const ids=new Set(rows.map(n=>n.id));const seed=ISR.news.filter(n=>!ids.has(n.id));el.innerHTML=rows.concat(seed).map(isrNewsCard).join('');}
async function showIsraelRadar(){
 show('israelradar');setTab('');setHash('#/israel-radar');document.title='رادار اسرائیل؛ انتخابات و پیامدها برای ایران | پندار';
 const root=document.getElementById('israel-radar-content');root.innerHTML='<div class="spinner"></div>';
 try{await loadISRadar();renderIsraelRadar();await loadISRNews();if(currentRoute().split('/').includes('israel-radar'))renderIsraelRadar();}catch(_){root.innerHTML='<div class="state">بارگذاری رادار انجام نشد. <button onclick="showIsraelRadar()">تلاش دوباره</button></div>';}
}
function renderIsraelRadar(){
 const root=document.getElementById('israel-radar-content');if(!root||!ISR)return;
 const days=Math.max(0,Math.ceil((Date.parse(ISR.election_date+'T00:00:00+02:00')-Date.now())/86400000));
 const pollAge=(Date.now()-Date.parse(ISR.poll.date+'T00:00:00Z'))/86400000;
 root.innerHTML=`<nav class="isr-radar-nav"><a href="/radar/">رادارهای پندار</a><a href="/us-radar/">رادار آمریکا ←</a></nav>
 <header class="isr-hero"><div><small>PENDAR · ISRAEL RADAR</small><h1>رادار اسرائیل</h1><p>انتخابات، ائتلاف‌ها و سیاست اسرائیل؛ با نگاه به پیامدهایشان برای ایران.</p><a href="${esc(ISR.election_source)}" target="_blank" rel="noopener">انتخابات: ${esc(isrDate(ISR.election_date))} · ۲۷ اکتبر ۲۰۲۶ ↗</a></div><div class="isr-count"><b>${faN(days)}</b><span>${days?'روز تا انتخابات':'روز؛ موعد رأی‌گیری رسیده است'}</span></div></header>
 <div class="isr-facts"><article><b>۱۲۰</b><span>کرسی پارلمان؛ کنست</span></article><article><b>۶۱</b><span>کرسی برای اکثریت مطلق</span></article><article><b>۳٫۲۵٪</b><span>حد نصاب ورود به پارلمان</span></article></div>
 <nav class="isr-jump" aria-label="بخش‌های رادار"><button onclick="document.getElementById('isr-polls').scrollIntoView({behavior:'smooth'})">نقشه کرسی‌ها</button><button onclick="document.getElementById('isr-coalition').scrollIntoView({behavior:'smooth'})">ائتلاف بساز</button><button onclick="document.getElementById('isr-people').scrollIntoView({behavior:'smooth'})">چهره‌ها</button><button onclick="document.getElementById('isr-iran').scrollIntoView({behavior:'smooth'})">ایران</button></nav>
 <section id="isr-polls"><div class="isr-section-head"><h2>نقشه کرسی‌ها</h2><span>${esc(ISR.poll.publisher)} · ${esc(isrDate(ISR.poll.date))}</span></div><p class="isr-caption">${esc(ISR.poll.kind)} · ${esc(ISR.poll.pollster)} · ${faN(ISR.poll.sample)} پاسخ‌دهنده${pollAge>14?' · این نظرسنجی بیش از دو هفته قدمت دارد':''}</p><div class="isr-seat-grid" role="img" aria-label="توزیع ۱۲۰ کرسی در نظرسنجی کان، ۴ اکتبر">${ISR.parties.flatMap(p=>Array.from({length:p.seats},()=>`<i style="background:${p.color}" title="${esc(p.name_fa)}: ${faN(p.seats)} کرسی"></i>`)).join('')}</div>
 <div class="isr-party-list">${ISR.parties.map(p=>`<article class="isr-party"><div class="isr-party-top"><h3><i style="background:${p.color}"></i>${esc(p.name_fa)}</h3><b>${faN(p.seats)} <small>کرسی</small></b></div><div class="isr-bar"><span style="width:${p.seats/30*100}%;background:${p.color}"></span></div><p>${esc(p.leader_fa)} · ${esc(p.orientation_fa)}</p>${p.handles.map(h=>`<a href="/figure/${h}/">${esc(ISR.people.find(x=>x.handle===h)?.name_fa||h)} ←</a>`).join(' ')}</article>`).join('')}</div><a class="isr-source" href="${esc(ISR.poll.url)}" target="_blank" rel="noopener">جدول و تصویر نظرسنجی در منبع اصلی ↗</a></section>
 <section id="isr-coalition"><div class="isr-section-head"><h2>ائتلاف بساز</h2><span>بر پایه همین نظرسنجی</span></div><p>احزاب را انتخاب کن و ببین مجموع کرسی‌ها به ۶۱ می‌رسد یا نه. این ابزار فقط جمع کرسی‌هاست؛ توافق سیاسی و امکان تشکیل دولت را پیش‌بینی نمی‌کند.</p><div class="isr-coalition-layout"><div class="isr-choices">${ISR.parties.map(p=>`<label><input type="checkbox" ${ISR_SELECTED.has(p.id)?'checked':''} onchange="isrToggleParty('${p.id}',this.checked)"><span>${esc(p.name_fa)}</span><b>${faN(p.seats)}</b></label>`).join('')}</div><div class="isr-coalition-result"><div id="isr-coalition-total" aria-live="polite"></div><div class="isr-coalition-track"><span id="isr-coalition-progress"></span><i title="۶۱ کرسی؛ اکثریت" style="right:${61/120*100}%"></i></div><small>عبور از این خط، به معنی توافق احزاب نیست.</small></div></div></section>
 <section><div class="isr-section-head"><h2>خبرهای رادار</h2><select aria-label="نوع خبر" onchange="isrSetNewsFilter(this.value)"><option value="all" ${ISR_NEWS_FILTER==='all'?'selected':''}>همه خبرهای اسرائیل</option><option value="election" ${ISR_NEWS_FILTER==='election'?'selected':''}>انتخابات و سیاست داخلی</option></select></div><p class="isr-caption">خبرهای فارسی از سرخط پندار؛ مرتب‌شده بر اساس زمان انتشار.</p><div id="isr-news" class="isr-news-grid"></div></section>
 <section id="isr-people"><div class="isr-section-head"><h2>چهره‌های رقابت</h2><span>معرفی و خبرهای مرتبط</span></div><div class="isr-people-grid">${ISR.people.map(isrPersonCard).join('')}</div></section>
 <section id="isr-iran"><div class="isr-section-head"><h2>درباره ایران چه می‌گویند؟</h2><span>مواضع مستند؛ با تاریخ و منبع</span></div><div class="isr-news-grid">${ISR.iran_positions.map(isrPositionCard).join('')}</div><p class="isr-caption">اختلاف با نتانیاهو به‌تنهایی نشانه تفاوت سیاست درباره ایران نیست؛ موضع هر فرد جداگانه بررسی می‌شود.</p></section>
 <section class="isr-guide"><h2>انتخابات اسرائیل در چند دقیقه</h2><details open><summary>کنست چیست و رأی به چه کسی داده می‌شود؟</summary><p>کنست پارلمان ۱۲۰ نفره اسرائیل است. رأی‌دهندگان به فهرست‌های حزبی رأی می‌دهند. کرسی‌ها میان فهرست‌هایی که حداقل ۳٫۲۵ درصد آرای معتبر را گرفته‌اند توزیع می‌شود.</p></details><details><summary>حزب اول الزاماً نخست‌وزیر می‌شود؟</summary><p>خیر؛ توان تشکیل دولت و جلب حمایت پارلمان تعیین‌کننده است. احزاب معمولاً برای این کار ائتلاف می‌کنند. عدد ۶۱ در این صفحه معیار اکثریت مطلق کرسی‌هاست.</p></details><details><summary>چرا برای ایران مهم است؟</summary><p>ترکیب دولت می‌تواند بر تصمیم‌های امنیتی، رابطه با آمریکا، دیپلماسی و برخورد با جمهوری اسلامی اثر بگذارد. از عدد نظرسنجی نمی‌توان نتیجه قطعی درباره جنگ یا مذاکره گرفت.</p></details><a href="${esc(ISR.system_source)}" target="_blank" rel="noopener">راهنمای رسمی انتخابات ↗</a></section>`;
 isrRefreshCoalition();isrRenderNews();
}
function showRadarHub(){show('radar');setTab('');setHash('#/radar');document.title='رادارهای پندار | آمریکا و اسرائیل';document.getElementById('radar-content').innerHTML=`<header class="isr-hero"><div><small>PENDAR · RADARS</small><h1>رادارهای پندار</h1><p>رقابت‌های سیاسی جهان و پیامدهایشان برای ایران؛ خبر، چهره و داده در یک جا.</p></div></header><div class="isr-hub-grid"><a href="/us-radar/"><small>آمریکا · ۲۰۲۶</small><h2>رادار آمریکا</h2><p>انتخابات میان‌دوره‌ای، رقابت‌های کنگره و مواضع نامزدها درباره ایران.</p><b>وارد رادار شو ←</b></a><a href="/israel-radar/"><small>اسرائیل · ۲۰۲۶</small><h2>رادار اسرائیل</h2><p>احزاب، نقشه کرسی‌ها، ائتلاف‌سازی و مواضع چهره‌ها درباره ایران.</p><b>وارد رادار شو ←</b></a></div>`;}
