const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const ctx={window:{},URL,Map,Set,Date,Promise,AbortController,setTimeout,clearTimeout,_bookNorm:v=>String(v||'').replace(/ي/g,'ی').replace(/ك/g,'ک').replace(/‌/g,' ').trim().toLowerCase()};vm.createContext(ctx);
vm.runInContext(fs.readFileSync('web-static/book-places.js','utf8'),ctx);vm.runInContext(fs.readFileSync('web-static/book-market-ui.js','utf8'),ctx);
const run=s=>vm.runInContext(s,ctx);
assert.equal(run('_bookMarketPlace("سراسر ایران").cities.length'),31);assert.equal(run('_bookMarketPlace("استان تهران").cities.length'),1);assert.equal(run('_bookMarketPlace("تهران").slug'),'tehran');assert.equal(run('_bookMarketPlace("شهر خیالی")'),null);assert.equal(run('window.__BOOK_PLACES__.cities.length'),1177);
assert.equal(run('_bookAdPhoto("https://s100.divarcdn.com/a.webp")'),'https://s100.divarcdn.com/a.webp');for(const url of ['javascript:alert(1)','https://s100.divarcdn.com.attacker.test/a','https://attacker.test/image.jpg'])assert.equal(ctx._bookAdPhoto(url),'');
const rpc={result:{content:[{type:'text',text:'{"items":[]}'}]}};assert.equal(ctx._bookMarketDecode(JSON.stringify(rpc)).items.length,0);assert.equal(ctx._bookMarketDecode('event: message\ndata: '+JSON.stringify(rpc)+'\n\n').items.length,0);for(const value of [{error:{code:1}},{result:{isError:true}},{result:{content:[{type:'text',text:'{"error":"failed"}'}]}}])assert.throws(()=>ctx._bookMarketDecode(JSON.stringify(value)));
assert.throws(()=>ctx._bookMarketNormalize({unknown_cities:['bad']},'رمان'));const card={token:'abc',url:'https://divar.ir/v/abc',title:'رمان خوب',price_toman:50,thumbnail:'https://evil.test/x'};assert.equal(ctx._bookMarketNormalize({items:[card]},'رمان')[0].thumbnail,'');assert.equal(ctx._bookMarketNormalize({items:[{...card,negotiable:true}]},'رمان')[0].asking_price_toman,null);assert.equal(ctx._bookMarketNormalize({items:[{...card,title:'خدمات کتابخانه'}]},'رمان').length,0);
let calls=0;ctx.fetch=async()=>{calls++;return {ok:true,text:async()=>JSON.stringify(rpc)}};(async()=>{await assert.rejects(ctx._bookMarketRPC('search_ads',{},()=>false));assert.equal(calls,0);console.log('Book market city scope, RPC, preview and cancellation checks passed')})().catch(e=>{console.error(e);process.exitCode=1});
