const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const now = Date.parse('2026-10-08T18:00:00Z');
const escape = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const elements = {'home-people-strip':{style:{}},'home-people-list':{innerHTML:''}};
const context = vm.createContext({console,URL,Date:class extends Date {static now(){return now;}},document:{getElementById:id=>elements[id]},esc:escape});
for (const file of ['figures-core.js','home.js']) vm.runInContext(fs.readFileSync(path.join(__dirname,'../../web-static',file),'utf8'),context);
const posts = [{editorial:true,platform:'transcript',published_at:null,recorded_at:'2026-10-08T16:00:00Z'}];
assert.equal(context.figureActivityTime(posts[0]),Date.parse(posts[0].recorded_at));
assert.equal(context.figureActivityTime({...posts[0],editorial:false}),0,'non-editorial collection date must not become activity');
assert.equal(context.figureActivityTime({...posts[0],recorded_at:'2027-01-01T00:00:00Z'}),0,'future registration must not dominate');
assert.equal(context.figureTextParagraphs({summary_fa:'<script>x</script>\n\nمتن دوم'}),'<p>&lt;script&gt;x&lt;/script&gt;</p><p>متن دوم</p>');
assert(context.homeFigurePriority({posts},now)<context.homeFigurePriority({handle:'abbas-souri',posts:[{published_at:'2026-10-08T17:00:00Z'}]},now));
assert.equal(context.homeFigurePriority({posts:[{...posts[0],recorded_at:'2026-10-05T16:00:00Z'}]},now),5,'old interviews must rotate out of priority');
const handles = ['nader-rafiei','bahadaf','mostafadaneshgar','yaghma-golrouee'];
const figures = handles.map((handle,i)=>({handle,name_fa:handle,field:'media',posts,avatar:i?'portrait.jpg':''}));
for(let i=0;i<20;i++) figures.push({handle:'regular-'+i,name_fa:'regular-'+i,field:'media',avatar:'photo.jpg',posts:[{published_at:'2026-10-08T17:00:00Z'}]});
figures.push({handle:'radar',name_fa:'radar',us_radar:true,posts,avatar:'photo.jpg'},{handle:'news-person',name_fa:'news-person',field:'news',posts,avatar:'photo.jpg'});
context.loadFigures=async()=>({figures});context.loadCanonicalEntities=async()=>({entities:[]});
(async()=>{
 await context.renderHomePeople();
 const html=elements['home-people-list'].innerHTML;
 for(const handle of handles)assert(html.includes(`openFigure('${handle}')`),handle+' missing from home strip');
 assert.equal((html.match(/class="home-person"/g)||[]).length,14);
 assert(!html.includes("openFigure('radar')")&&!html.includes("openFigure('news-person')"));
 assert(html.includes('home-person-initial'),'a missing portrait must retain the profile');
 assert(!html.includes("closest('.home-person')?.remove()"),'a broken image must not remove the person');
 assert(!html.includes('has-recent-video'),'registration must not create a fresh-video badge');
 assert.equal(posts[0].published_at,null,'source date remains unknown');
 console.log('PASS: fresh interview discovery, missing portraits, rotation, source dates and escaped paragraphs');
})().catch(error=>{console.error(error);process.exitCode=1});
