const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const elements=new Map();
const el=id=>{if(!elements.has(id))elements.set(id,{innerHTML:'',textContent:'',isConnected:true});return elements.get(id)};
const now=Date.now(),date=age=>new Date(now-age*86400000).toISOString();
const row=(id,title,categories,extra={})=>({id,title_fa:title,categories,published_at:date(1),url:`https://publisher.example/${id}`,source:{name:'رسانهٔ اصلی'},...extra});
const items=[row('ai','هوش مصنوعی در سفارش‌گیری رستوران',['restaurant_technology_ai']),row('menu','هزینه و سود منو',['food_cost_pricing']),row('cafe','باریستا و قهوه',['beverage']),row('farm','خبر کشاورزی',['food_industry']),row('blocked','منو',['menu_product_innovation'],{translation_quality:{status:'block'}}),row('future','منوی آینده',['menu_product_innovation'],{published_at:date(-1)}),row('old','منوی قدیمی',['menu_product_innovation'],{published_at:date(31)}),row('duplicate','نسخهٔ تکراری',['restaurant_technology_ai'],{url:'https://publisher.example/ai'})];
let requests=0,fail=false;
const ctx={console,Date,Number,Promise,URL,AbortSignal,window:{},DATA:'data',document:{getElementById:el,querySelectorAll:()=>[]},esc:s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/"/g,'&quot;'),faN:String,grp:String,setHash:()=>{},show:()=>{},setTab:()=>{},getJSON:async()=>[],fetch:async()=>{requests++;if(fail)throw Error('offline');return {ok:true,json:async()=>({items})}}};
vm.createContext(ctx);
for(const path of ['web-static/market-nabzesh.js','web-static/market-weather.js','web-static/diner.js'])vm.runInContext(fs.readFileSync(path,'utf8'),ctx);
(async()=>{
 const [one,two]=await Promise.all([ctx.loadMarketFoodData(),ctx.loadMarketFoodData()]);
 assert.equal(requests,1);assert.equal(one,two);
 await ctx.showDiner();await ctx.renderDinerNews();
 const page=el('diner-content').innerHTML;
 assert.match(page,/href="\/@nima-afshar-naderi\/"/);assert.match(page,/href="\/@soufia-abdollahi\/"/);
 let news=el('diner-news').innerHTML;
 assert.match(news,/هوش مصنوعی در سفارش‌گیری/);assert.match(news,/هزینه و سود منو/);assert.match(news,/باریستا و قهوه/);
 for(const hidden of ['خبر کشاورزی','منوی آینده','منوی قدیمی','نسخهٔ تکراری'])assert.doesNotMatch(news,new RegExp(hidden));
 assert.match(news,/رسانهٔ اصلی/);assert.match(news,/href="https:\/\/publisher.example\/ai"/);
 ctx.setDinerNewsFilter('menu');news=el('diner-news').innerHTML;
 assert.match(news,/هزینه و سود منو/);assert.doesNotMatch(news,/هوش مصنوعی در سفارش‌گیری/);
 ctx.setDinerNewsFilter('cafe');assert.match(el('diner-news').innerHTML,/باریستا و قهوه/);assert.doesNotMatch(el('diner-news').innerHTML,/هزینه و سود منو/);
 ctx.setDinerNewsFilter('ai');assert.match(el('diner-news').innerHTML,/هوش مصنوعی در سفارش‌گیری/);
 assert.match(ctx.renderRetro(),/diner-profile-feature" href="\/@soufia-abdollahi\/"/);
 vm.runInContext('marketFoodCache=null',ctx);fail=true;await ctx.renderDinerNews();
 assert.match(el('diner-news').innerHTML,/خبرها فعلاً دریافت نشدند/);assert.match(el('diner-news').innerHTML,/تلاش دوباره/);
 fail=false;await ctx.renderDinerNews();assert.match(el('diner-news').innerHTML,/هوش مصنوعی در سفارش‌گیری/);
 console.log('Diner news filters, attribution, shared fetch, profile links and recovery passed.');
})().catch(error=>{console.error(error);process.exitCode=1});
