"""Canonical Jan-e Jaraid source registry.

News feeds listed in PRESS_FEEDS were already used/verified by the main ingestion
pipeline. Jan-e Jaraid reuses those exact endpoints instead of guessing new RSS
URLs. Sources without a verified feed remain visible and can fall back to HTML
or a future dedicated adapter.

Source-level editorial exclusions in app.ingestion.service apply to every
collector, including pinned feeds and article-page fetches.
"""

# Verified publisher feeds. Keep names aligned with PRESS_REGISTRY / the public
# press directory so article groups land on the correct source page.
PRESS_FEEDS = {
    # Iranian magazines / periodicals
    "بخارا": "https://bukharamag.com/feed",

    # Iran — agencies, news sites and newspapers
    "ایرنا": "https://www.irna.ir/rss",
    "ایسنا": "https://www.isna.ir/rss",
    "مهر": "https://www.mehrnews.com/rss",
    "فارس": "https://farsnews.ir/rss",
    "خبرآنلاین": "https://www.khabaronline.ir/rss",
    "همشهری": "https://www.hamshahrionline.ir/rss",
    "خبرگزاری صداوسیما": "https://www.iribnews.ir/fa/rss/allnews",
    "باشگاه خبرنگاران جوان": "https://www.yjc.ir/fa/rss/allnews",
    "تابناک": "https://www.tabnak.ir/fa/rss/allnews",
    "فرارو": "https://fararu.com/fa/rss/allnews",
    "انتخاب": "https://www.entekhab.ir/fa/rss/allnews",
    "عصر ایران": "https://www.asriran.com/fa/rss/allnews",
    "فردانیوز": "https://www.fardanews.com/fa/rss/allnews",
    "رویداد۲۴": "https://www.rouydad24.ir/fa/rss/allnews",
    "آفتاب‌نیوز": "https://aftabnews.ir/fa/rss/allnews",
    "مشرق نیوز": "https://www.mashreghnews.ir/rss",
    "انصاف نیوز": "https://www.ensafnews.com/feed",
    "پیام ما": "https://payamema.ir/feed",
    "شرق": "https://www.sharghdaily.com/fa/rss/allnews",
    "اعتماد": "https://www.etemadonline.com/fa/rss/allnews",
    "دنیای اقتصاد": "https://donya-e-eqtesad.com/fa/rss/allnews",
    "ایلنا": "https://www.ilna.ir/fa/rss/allnews",
    "تسنیم": "https://www.tasnimnews.com/fa/rss/feed/0/8/0/%D8%A2%D8%AE%D8%B1%DB%8C%D9%86-%D8%A7%D8%AE%D8%A8%D8%A7%D8%B1",
    "آنا": "https://ana.ir/fa/rss/allnews",
    "اقتصادنیوز": "https://www.eghtesadnews.com/fa/rss/allnews",
    "اکوایران": "https://ecoiran.com/fa/rss/allnews",
    "دیپلماسی ایرانی": "https://irdiplomacy.ir/fa/rss",
    "جماران": "https://www.jamaran.news/fa/rss/allnews",
    "میزان": "https://www.mizanonline.ir/fa/rss/allnews",
    "شفقنا فارسی": "https://fa.shafaqna.com/feed/",

    # Persian-language international / diaspora
    ("خبرگزاری ایرانشهر","https://www.iranshahrnewsagency.com/","fa","diaspora"),
    ("اپک تایمز فارسی","https://persianepochtimes.com/","fa","diaspora"),
    ("استکهلمیان","https://www.stockholmian.com/","fa","diaspora"),
    ("پرژن میرور","https://www.persianmirror.ca/","fa","diaspora"),
    ("مجله جوانان","https://javanan.com/","fa","diaspora"),
    "اخبار روز": "https://akhbar-rooz.com/feed/",
    "رادیو زمانه": "http://radiozamaneh.com/rss.xml",
    "رادیو فردا": "https://www.radiofarda.com/api/zrttpol-vomx-tpeoogpi",
    "ایران‌وایر": "https://iranwire.com/feed/",
    "مرکز حقوق بشر در ایران": "https://iranhumanrights.org/feed/",
    "بی‌بی‌سی فارسی": "https://feeds.bbci.co.uk/persian/rss.xml",
    "ایران اینترنشنال": "https://www.iranintl.com/feed",
    "دویچه‌وله فارسی": "https://rss.dw.com/rdf/rss-per-all",
    "یورونیوز فارسی": "https://parsi.euronews.com/rss",
    "کیهان لندن": "https://kayhan.london/feed/",
    "زیتون": "https://www.zeitoons.com/feed",
    "ایندیپندنت فارسی": "https://www.independentpersian.com/rss.xml",
    "صدای آمریکا فارسی": "https://ir.voanews.com/api/zmgqoe$mvi",
    "العربیه فارسی": "https://farsi.alarabiya.net/tools/rss",

    # International
    "BBC": "http://feeds.bbci.co.uk/news/world/rss.xml",
    "El País": "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/internacional/portada",
    "The Guardian": "https://www.theguardian.com/world/rss",
    "Al Jazeera": "https://www.aljazeera.com/xml/rss/all.xml",
    "Press TV": "https://www.presstv.ir/rss",
    "Tehran Times": "https://www.tehrantimes.com/rss",
    "Al-Alam": "https://www.alalam.ir/rss",
    "Al-Monitor": "https://www.al-monitor.com/rss",
    "France 24": "https://www.france24.com/en/rss",
    "RFI": "https://www.rfi.fr/en/rss",
    "Anadolu Ajansı": "https://www.aa.com.tr/en/rss/default?cat=guncel",
    "CNN": "http://rss.cnn.com/rss/edition_world.rss",
    "NPR": "https://feeds.npr.org/1004/rss.xml",
    "CNBC": "https://www.cnbc.com/id/100727362/device/rss/rss.html",
    "Sky News": "https://feeds.skynews.com/feeds/rss/world.xml",
    "El Mundo": "https://e00-elmundo.uecdn.es/elmundo/rss/internacional.xml",
    "La Vanguardia": "https://www.lavanguardia.com/rss/internacional.xml",
    "BBC Mundo": "https://feeds.bbci.co.uk/mundo/rss.xml",
    "CNN en Español": "https://cnnespanol.cnn.com/feed/",
    "DW Español": "https://rss.dw.com/rdf/rss-sp-all",
    "RTVE Noticias": "https://www.rtve.es/api/noticias.rss",
    "ABC España": "https://www.abc.es/rss/feeds/abc_Internacional.xml",
    "El Confidencial": "https://rss.elconfidencial.com/mundo/",
    "France 24 Español": "https://www.france24.com/es/rss",
    "DW": "https://rss.dw.com/rdf/rss-en-all",

    # Specialist sources already verified by the main pipeline
    "The Verge": "https://www.theverge.com/rss/index.xml",
    "ورزش سه": "https://www.varzesh3.com/rss/all",
    "دیجیاتو": "https://digiato.com/feed",
    "زومیت": "https://www.zoomit.ir/feed",
    "گیمفا": "https://gamefa.com/feed/",
    "سلامت نیوز": "http://salamatnews.com/rss.xml",
}


# Curated YouTube channels treated as first-class Jan-e Jaraid sources.
# Store canonical @handles here; the monitor resolves the real channel_id at runtime
# instead of trusting manually copied IDs (which are easy to mismatch).
YOUTUBE_PRESS_SOURCES = {
    "Pump VOD": "https://www.youtube.com/channel/UCMPdfQnOy5Vu07j6C141FWQ",
    "Rok Show": "https://www.youtube.com/channel/UCeLPadoZ4vXAM13iyvivhBg",
    "Baziya (Ali Zia)": "https://www.youtube.com/channel/UC8LVufbnNQkU20_fyycIL7A",
    "Manoto TV": "https://www.youtube.com/channel/UCnUdm0u-2FRffBnxQYHuTHA",
    "Farhikhtegan Online": "https://www.youtube.com/channel/UCq05uUbwwT1YtxU26Cfwdfw",
    "Ivar Farhadi": "https://www.youtube.com/channel/UCpKTQ7EgNIb5nMahQLdMthw",
    "Chanteh Podcast": "https://www.youtube.com/channel/UCvCbxRVG7kyB0uwSOK0eLnQ",
    "مسعود بهنود": "https://www.youtube.com/@mbehnoud",
    "دیدارنیوز": "https://www.youtube.com/@didarnews",
    "همشهری TV": "https://www.youtube.com/@hamshahritv",
    "ایران فردا TV": "https://www.youtube.com/@Iranefarda_TV",
    "جمشید چالنگی": "https://www.youtube.com/@JamshidChalangi1",
    "بزرگمهر شرف‌الدین": "https://www.youtube.com/@BozorgmehrSharafedin",
    "کارگاه": "https://www.youtube.com/@Kargahnet",
    "دگم نباش": "https://www.youtube.com/@DogmNabash",
    "۷ آبان": "https://www.youtube.com/@7Aban_h",
    "دکتر فرهنگ هلاکویی": "https://www.youtube.com/@dr.holakoueeofficialchannel",
    "Channel One TV": "https://www.youtube.com/@ChanelOneTVIranian",
    "Zabane.z": "https://www.youtube.com/@Zabane.z",
    "رسانه آلترناتیو": "https://www.youtube.com/@ResanehAlternative",
    "Persian Clubhouse": "https://www.youtube.com/@persianclubhouse113",
    "Fuse Podcast": "https://www.youtube.com/@fusepodcast",
    "Studio Patt": "https://www.youtube.com/@Studio_patt",
    "نزدیک‌تر تاک": "https://www.youtube.com/@nazdiktar_talk",
    "Cimorg Futures": "https://www.youtube.com/@CimorgFutures",
    "Azad Social": "https://www.youtube.com/@azadsocial",
    "خط فرضی": "https://www.youtube.com/@Khattefarzi",
    "کاغذ سیاست": "https://www.youtube.com/@kaghazesiasat",
    "Yazdan Talkshow": "https://www.youtube.com/@yazdantalkshow",
    "Jomhouri Street": "https://www.youtube.com/@jomhouristreet",
    "Tomorrow’s Horizon": "https://www.youtube.com/@TomorrowsHorizon2024",
    "Sajadni Movies": "https://www.youtube.com/@sajadniMovies",
    "Khashayar Stories": "https://www.youtube.com/@Khashayarstories",
    "Sepehris Cult": "https://www.youtube.com/@SepehrisCult",
    "احسان منصوری": "https://www.youtube.com/@ehsanmansoori",
    "اشکان زارع": "https://www.youtube.com/@ashkan_zare",
    "جدال": "https://youtube.com/jedaaltv",
    "سیمرغ طلایی": "https://www.youtube.com/@GoldenSimorgh-d4u",
    "تلویزیون هوش مصنوعی سیمرغ": "https://www.youtube.com/channel/UCrdxqvmkMQrohT0Setx--pw",
}


# Verified YouTube RSS feeds supplied for curated video sources.
PRESS_FEEDS.update({
    "Chanteh Podcast": "https://www.youtube.com/feeds/videos.xml?channel_id=UCvCbxRVG7kyB0uwSOK0eLnQ",
    "Zabane.z": "https://www.youtube.com/feeds/videos.xml?channel_id=UC6ovmNwfP1IGZK2hu211tIQ",
    "۷ آبان": "https://www.youtube.com/feeds/videos.xml?channel_id=UCsvEKD1jr4i0gKAJ5JZfHbA",
    "Ivar Farhadi": "https://www.youtube.com/feeds/videos.xml?channel_id=UCpKTQ7EgNIb5nMahQLdMthw",
    "Farhikhtegan Online": "https://www.youtube.com/feeds/videos.xml?channel_id=UCq05uUbwwT1YtxU26Cfwdfw",
    "Manoto TV": "https://www.youtube.com/feeds/videos.xml?channel_id=UCnUdm0u-2FRffBnxQYHuTHA",
    "Cimorg Futures": "https://www.youtube.com/feeds/videos.xml?channel_id=UCOqLHxtUgG4JjE088iidj2g",
    "Persian Clubhouse": "https://www.youtube.com/feeds/videos.xml?channel_id=UCaX72gRAke5eL4Dl5ikc2UQ",
    "Baziya (Ali Zia)": "https://www.youtube.com/feeds/videos.xml?channel_id=UC8LVufbnNQkU20_fyycIL7A",
    "Rok Show": "https://www.youtube.com/feeds/videos.xml?channel_id=UCeLPadoZ4vXAM13iyvivhBg",
    "Pump VOD": "https://www.youtube.com/feeds/videos.xml?channel_id=UCMPdfQnOy5Vu07j6C141FWQ",
})

PRESS_REGISTRY = [
    # Iran — agencies / news portals
    ("فرادید","https://faradeed.ir/","fa","iran-agency"),
    ("جام‌جم آنلاین","https://jamejamonline.ir/","fa","iran-paper"),
    ("ایران امروز","https://iran-emrooz.net/","fa","diaspora"),
    ("رسانه رهبر انقلاب اسلامی","https://rahbar.ir/","fa","iran-agency"),
    ("ایرنا","https://www.irna.ir","fa","iran-agency"),
    ("ایسنا","https://www.isna.ir","fa","iran-agency"),
    ("مهر","https://www.mehrnews.com","fa","iran-agency"),
    ("فارس","https://farsnews.ir","fa","iran-agency"),
    ("خبرآنلاین","https://www.khabaronline.ir","fa","iran-agency"),
    ("خبرگزاری صداوسیما","https://www.iribnews.ir","fa","iran-agency"),
    ("باشگاه خبرنگاران جوان","https://www.yjc.ir","fa","iran-agency"),
    ("تابناک","https://www.tabnak.ir","fa","iran-agency"),
    ("فرارو","https://fararu.com","fa","iran-agency"),
    ("انتخاب","https://www.entekhab.ir","fa","iran-agency"),
    ("عصر ایران","https://www.asriran.com","fa","iran-agency"),
    ("فردانیوز","https://www.fardanews.com","fa","iran-agency"),
    ("رویداد۲۴","https://www.rouydad24.ir","fa","iran-agency"),
    ("آفتاب‌نیوز","https://aftabnews.ir","fa","iran-agency"),
    ("مشرق نیوز","https://www.mashreghnews.ir","fa","iran-agency"),
    ("انصاف نیوز","https://www.ensafnews.com","fa","iran-agency"),
    ("ایلنا","https://www.ilna.ir","fa","iran-agency"),
    ("تسنیم","https://www.tasnimnews.com","fa","iran-agency"),
    ("آنا","https://ana.ir","fa","iran-agency"),
    ("اقتصادنیوز","https://www.eghtesadnews.com","fa","iran-agency"),
    ("اکوایران","https://ecoiran.com","fa","iran-agency"),
    ("دیپلماسی ایرانی","https://irdiplomacy.ir","fa","iran-agency"),
    ("جماران","https://www.jamaran.news","fa","iran-agency"),
    ("میزان","https://www.mizanonline.ir","fa","iran-agency"),
    ("شفقنا فارسی","https://fa.shafaqna.com","fa","iran-agency"),

    # Iran — newspapers
    ("همشهری","https://www.hamshahrionline.ir","fa","iran-paper"),
    ("پیام ما","https://payamema.ir","fa","iran-paper"),
    ("شرق","https://www.sharghdaily.com","fa","iran-paper"),
    ("اعتماد","https://www.etemadonline.com","fa","iran-paper"),
    ("دنیای اقتصاد","https://donya-e-eqtesad.com","fa","iran-paper"),

    # Persian-language international / diaspora
    ("اخبار روز","https://akhbar-rooz.com","fa","diaspora"),
    ("رادیو زمانه","https://www.radiozamaneh.com","fa","diaspora"),
    ("رادیو فردا","https://www.radiofarda.com","fa","diaspora"),
    ("ایران‌وایر","https://iranwire.com/fa/","fa","diaspora"),
    ("مرکز حقوق بشر در ایران","https://iranhumanrights.org","fa","diaspora"),
    ("بی‌بی‌سی فارسی","https://www.bbc.com/persian","fa","diaspora"),
    ("ایران اینترنشنال","https://www.iranintl.com","fa","diaspora"),
    ("دویچه‌وله فارسی","https://www.dw.com/fa-ir","fa","diaspora"),
    ("یورونیوز فارسی","https://parsi.euronews.com","fa","diaspora"),
    ("کیهان لندن","https://kayhan.london","fa","diaspora"),
    ("زیتون","https://www.zeitoons.com","fa","diaspora"),
    ("ایندیپندنت فارسی","https://www.independentpersian.com","fa","diaspora"),
    ("صدای آمریکا فارسی","https://ir.voanews.com","fa","diaspora"),
    ("العربیه فارسی","https://farsi.alarabiya.net","fa","diaspora"),

    # International news / newspapers
    ("BBC","https://www.bbc.com/news","en","world"),
    ("El País","https://elpais.com/internacional/","es","world"),
    ("The Guardian","https://www.theguardian.com","en","world"),
    ("Al Jazeera","https://www.aljazeera.com","en","world"),
    ("Press TV","https://www.presstv.ir","en","world"),
    ("Tehran Times","https://www.tehrantimes.com","en","world"),
    ("Al-Alam","https://www.alalam.ir","ar","world"),
    ("Al-Monitor","https://www.al-monitor.com","en","world"),
    ("France 24","https://www.france24.com/en/","en","world"),
    ("RFI","https://www.rfi.fr/en/","en","world"),
    ("Anadolu Ajansı","https://www.aa.com.tr/en","en","world"),
    ("CNN","https://www.cnn.com","en","world"),
    ("NPR","https://www.npr.org","en","world"),
    ("CNBC","https://www.cnbc.com/world/","en","world"),
    ("Sky News","https://news.sky.com","en","world"),
    ("El Mundo","https://www.elmundo.es","es","world"),
    ("La Vanguardia","https://www.lavanguardia.com","es","world"),
    ("BBC Mundo","https://www.bbc.com/mundo","es","world"),
    ("CNN en Español","https://cnnespanol.cnn.com","es","world"),
    ("DW Español","https://www.dw.com/es","es","world"),
    ("RTVE Noticias","https://www.rtve.es/noticias/","es","world"),
    ("ABC España","https://www.abc.es","es","world"),
    ("El Confidencial","https://www.elconfidencial.com","es","world"),
    ("France 24 Español","https://www.france24.com/es/","es","world"),
    ("DW","https://www.dw.com","en","world"),

    # Specialist verified feeds
    ("The Verge","https://www.theverge.com","en","world"),
    ("ورزش سه","https://www.varzesh3.com","fa","iran-agency"),
    ("دیجیاتو","https://digiato.com","fa","iran-agency"),
    ("زومیت","https://www.zoomit.ir","fa","iran-agency"),
    ("گیمفا","https://gamefa.com","fa","iran-agency"),
    ("سلامت نیوز","https://www.salamatnews.com","fa","iran-agency"),

    # Curated YouTube channels / video podcasts
    ("مسعود بهنود","https://www.youtube.com/@mbehnoud","fa","youtube"),
    ("دیدارنیوز","https://www.youtube.com/@didarnews","fa","youtube"),
    ("همشهری TV","https://www.youtube.com/@hamshahritv","fa","youtube"),
    ("ایران فردا TV","https://www.youtube.com/@Iranefarda_TV","fa","youtube"),
    ("جمشید چالنگی","https://www.youtube.com/@JamshidChalangi1","fa","youtube"),
    ("بزرگمهر شرف‌الدین","https://www.youtube.com/@BozorgmehrSharafedin","fa","youtube"),
    ("کارگاه","https://www.youtube.com/@Kargahnet","fa","youtube"),
    ("دگم نباش","https://www.youtube.com/@DogmNabash","fa","youtube"),
    ("۷ آبان","https://www.youtube.com/@7Aban_h","fa","youtube"),
    ("دکتر فرهنگ هلاکویی","https://www.youtube.com/@dr.holakoueeofficialchannel","fa","youtube"),
    ("Channel One TV","https://www.youtube.com/@ChanelOneTVIranian","fa","youtube"),
    ("Zabane.z","https://www.youtube.com/@Zabane.z","fa","youtube"),
    ("رسانه آلترناتیو","https://www.youtube.com/@ResanehAlternative","fa","youtube"),
    ("Persian Clubhouse","https://www.youtube.com/@persianclubhouse113","fa","youtube"),
    ("Fuse Podcast","https://www.youtube.com/@fusepodcast","fa","youtube"),
    ("Studio Patt","https://www.youtube.com/@Studio_patt","fa","youtube"),
    ("نزدیک‌تر تاک","https://www.youtube.com/@nazdiktar_talk","fa","youtube"),
    ("Cimorg Futures","https://www.youtube.com/@CimorgFutures","fa","youtube"),
    ("Azad Social","https://www.youtube.com/@azadsocial","fa","youtube"),
    ("خط فرضی","https://www.youtube.com/@Khattefarzi","fa","youtube"),
    ("کاغذ سیاست","https://www.youtube.com/@kaghazesiasat","fa","youtube"),
    ("Yazdan Talkshow","https://www.youtube.com/@yazdantalkshow","fa","youtube"),
    ("Jomhouri Street","https://www.youtube.com/@jomhouristreet","fa","youtube"),
    ("Tomorrow’s Horizon","https://www.youtube.com/@TomorrowsHorizon2024","fa","youtube"),
    ("Sajadni Movies","https://www.youtube.com/@sajadniMovies","fa","youtube"),
    ("Khashayar Stories","https://www.youtube.com/@Khashayarstories","fa","youtube"),
    ("Sepehris Cult","https://www.youtube.com/@SepehrisCult","fa","youtube"),
    ("احسان منصوری","https://www.youtube.com/@ehsanmansoori","fa","youtube"),
    ("اشکان زارع","https://www.youtube.com/@ashkan_zare","fa","youtube"),

    ("Chanteh Podcast","https://www.youtube.com/channel/UCvCbxRVG7kyB0uwSOK0eLnQ","fa","youtube"),
    ("Ivar Farhadi","https://www.youtube.com/channel/UCpKTQ7EgNIb5nMahQLdMthw","fa","youtube"),
    ("Farhikhtegan Online","https://www.youtube.com/channel/UCq05uUbwwT1YtxU26Cfwdfw","fa","youtube"),
    ("جدال","https://youtube.com/jedaaltv","fa","youtube"),
    ("سیمرغ طلایی","https://www.youtube.com/@GoldenSimorgh-d4u","fa","youtube"),
    ("تلویزیون هوش مصنوعی سیمرغ","https://www.youtube.com/channel/UCrdxqvmkMQrohT0Setx--pw","fa","youtube"),
    ("Manoto TV","https://www.youtube.com/channel/UCnUdm0u-2FRffBnxQYHuTHA","fa","youtube"),
    ("Baziya (Ali Zia)","https://www.youtube.com/channel/UC8LVufbnNQkU20_fyycIL7A","fa","youtube"),
    ("Rok Show","https://www.youtube.com/channel/UCeLPadoZ4vXAM13iyvivhBg","fa","youtube"),
    ("Pump VOD","https://www.youtube.com/channel/UCMPdfQnOy5Vu07j6C141FWQ","fa","youtube"),
    # Iranian periodicals — RSS/site/PDF fallback
    ("سپیده دانایی","https://www.magiran.com/magazine/5447","fa","iran-magazine"),
    ("ترجمان","https://tarjomaan.com","fa","iran-magazine"),
    ("مهرنامه","http://www.mehrnameh.ir","fa","iran-magazine"),
    ("دالان","http://www.dalan.media","fa","iran-magazine"),
    ("اندیشه پویا","https://andishepooya.ir","fa","iran-magazine"),
    ("آنگاه","https://angahmag.com","fa","iran-magazine"),
    ("روزآروز","https://roozarooz.com","fa","iran-magazine"),
    ("بخارا","https://bukharamag.com","fa","iran-magazine"),
    ("عصر اندیشه","https://asreandisheh.ir","fa","iran-magazine"),
    ("غروب","https://goroobonline.ir","fa","iran-magazine"),
    ("روزنامک","https://rooznamak-magazine.com","fa","iran-magazine"),
    ("چشم‌انداز ایران","https://meisami.net","fa","iran-magazine"),
    ("آزما","https://azmaonline.com","fa","iran-magazine"),
    ("آگاهی نو","https://agahino.com","fa","iran-magazine"),
    ("کتابنامه آگاهی نو","https://agahino.com","fa","iran-magazine"),
    ("وزن دنیا","https://vaznedonya.ir","fa","iran-magazine"),
]

# Registry policy: an entry without a working collector remains tracked backlog,
# not implicitly active. UI status is based on real collection/health output.
